[Part1 장성훈 week4] 이메일, 패스워드 검사
codeit-bootcamp-frontend/5-Weekly-Mission pull request #123
Opened 2024-03-05 09:16 UTC by hoonj170214

## 요구사항
- [x] 이메일 input에서 focus out 할 때, 값이 없을 경우 아래에 “이메일을 입력해 주세요.” 에러 메세지를 보입니다.
- [x] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해 주세요.” 에러 메세지를 보입니다.
- [x] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 아래에 “올바른 이메일 주소가 아닙니다.” 에러 메세지를 보입니다.
- [] 이메일: test@codeit.com, 비밀번호: codeit101 으로 로그인 시도할 경우, “/folder” 페이지로 이동합니다.
- [x] 이외의 로그인 시도의 경우, 이메일 input 아래에 “이메일을 확인해 주세요.”, 비밀번호 input 아래에 “비밀번호를 확인해 주세요.” 에러 메세지를 보입니다.
- [] input에 에러와 관련된 디자인은 좌측 상단의 Components 영역에 있는 디자인을 참고해 주세요.
- [x] 로그인 버튼 클릭 또는 Enter키 입력으로 로그인 실행돼야 합니다.

## 주요 변경점
- HTML  : email-input, password-input에 error-container 를 넣었습니다.
- JS 
- createErrorMessage : DOM 요소를 생성하는 함수입니다.
- appendErrorMessage : DOM 요소에 에러 메세지를 텍스트 노드에 할당하는 함수입니다.
- showErrorMessage : 조건에 따라 에러 메세지를 보여주는 함수입니다.
- validateForm : cta 버튼 이벤트 핸들러를 등록한 함수입니다. 

### 추후 보완사항
- /folder 페이지로 이동하는 것을 보충해야 합니다.
- CSS : 에러메세지를 나타내는 error-message 클래스네임을 만들어줬지만, CSS 스타일은 아직 입히지 않은 상태입니다.

## 멘토에게
- 자바스크립트 코드만 리뷰해주셔도 될 듯 합니다.
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-03-05 10:29 UTC, 1005hoon commented
@hoonj170214 

일단 공통적으로 프로젝트 구조가 변경될 수 있으면 좋겠어요! 
```
index.html - 메인 랜딩페이지
index.css - 메인 랜딩페이지에서 사용될 스타일
styles/
- common.css - 공통 활용될 스타일 (css reset / variable 등)
- ui.css - 공통 활용될 UI 스타일 (container, text-primary 등)
signup/ - 회원가입 페이지
- index.html
- style.css
- index.js
login/ - 로그인 페이지
- index.html
- style.css
- index.js
assets/
  images/
    - 이미지들 ...
```

이런식으로 각  폴더별로 활용될 html, css, js파일을 두고, 
공통 스크립트 또는 스타일의 경우 `styles` 폴더와 `scripts` 폴더를 두어 관리하는 형태가 조금 더 관리하기 좋을 듯 합니다!

2024-03-05 14:54 UTC, 1005hoon requested changes
@hoonj170214 

빠르게 구현 잘 하셨네요 ㅎㅎ 
다만 아직 미숙한부분들이 보여 코드 레벨에서 리뷰 남겨두었습니다. 
수정 반영하신 후 우측에 re-request 버튼 누르면 업데이트된 내용 체크할게요! 

추가적으로, 전반적으로 let을 변수선언 목적으로 많이 활용하고 계시는데
특별히 변수가 재선언 및 재할당이 될 필요가 없다면 const를 사용하시면 어떨까요?

2024-03-05 14:54 UTC, 1005hoon commented on index.html
> +    </nav>
@hoonj170214 

음 nav와 div의 위치가 바뀌었습니당! 
nav는 렌더링 될 내부 요소가 네비게이션의 집합임을 뜻하는 요소이고
div는 스타일 차원에 그룹을 위한 요소로 활용되어요. 

따라서 div로 감싸주고, nav 하위에 바로 링크들이 리스트되도록 하는게 더 좋아보입니다!

2024-03-05 14:54 UTC, 1005hoon commented on index.html
> +    </header>
@hoonj170214 

헤더의 경우 특정 콘텐츠의 헤딩이 담기는걸 표현하기 위한 요소로 활용되는데요, 
hero는 보통 헤딩을 담긴다는 표현보단 헤당 페이지의 특별한 섹션으로 평가되는 경우가 더 많은듯 해요.
따라서 header보단 이것도 section으로 두는건 어떨까요?

2024-03-05 14:54 UTC, 1005hoon commented on index.html
> +      </div>
@hoonj170214 

bem을 적용한다면 

```css
.hero
.hero-container
.hero-container__title
.hero-container__btn-cta
```
의 조합들로 구현을 해볼 수 있을듯해요

2024-03-05 14:54 UTC, 1005hoon commented on index.html
> +    <article>
@hoonj170214 

article태그의 경우 `문서, 페이지, 애플리케이션, 또는 사이트 안에서 독립적으로 구분해 배포하거나 재사용할 수 있는 구획`을 나타냅니다. 반면, 우리가 렌더링하는 이 부분의 경우, 독립적으로 구분할 수 있는 콘텐츠라기보단, 기능에대한 설명을 하고있는 섹션이 조금 더 맞을것 같아요. 따라서 article태그는 불필요한 마크업 렌더링으로 보입니다!

2024-03-05 14:54 UTC, 1005hoon commented on signin.html
> +          </div>
@hoonj170214 

이 그룹핑이 재활용될텐데요
특히 라벨과 인풋, 그리고 에러메시지를 보여주는 요소가 한 묶음으로 이메일, 비밀번호 모두 활용되죠.
이처럼 폼에서 라벨과 인풋등을 묶어서 관리하기 위한 요소를 `form-group` 이라는 이름으로 표현합니다. 
이 컨벤션에 맞춰 다음과 같이 마크업을 구성해보면 어떨까요? 

```css
.login-form
.login-form__body
.form-group
.form-group__label
.form-group__input
.form-group__error
```

2024-03-05 14:54 UTC, 1005hoon commented on signin.html
> +          </div>
@hoonj170214 

위에 설명한 마크업을 활용한다면 이런식으로 구현해볼 수 있겠죠
```html

    <form className="login-form">
      <div className="form-group">
        <label htmlFor="email" className="form-label">
          Email
        </label>
        <input
          type="email"
          id="email"
          className="form-input"
          placeholder="Enter your email"
        />
        <p className="email-error-message"></p>
      </div>
      <div className="form-group">
        <label htmlFor="password" className="form-label">
          Password
        </label>
        <input
          type="password"
          id="password"
          className="form-input"
          placeholder="Enter your password"
        />
        <button className="toggle-visibility"></button>
        <p className="password-error-message"></p>
      </div>
      <button type="submit" className="form-submit-button" disabled>
        Submit
      </button>
    </form>
```

2024-03-05 14:54 UTC, 1005hoon commented on index.html
> +      </section>
@hoonj170214 

오늘 멘토링때 이야기했던것처럼 역시 BEM 활용하는게 좋겠어요!

2024-03-05 14:54 UTC, 1005hoon commented on login/index.js
> +}
@hoonj170214 

굳이 에러메시지를 위한 DOM요소를 생성해 전달하는게 필요할까 싶어요! 
에러 메시지가 보여질 요소는 계속 존재하도록 두고, 텍스트밸류만 변경하는식으로 해보면 어떨까요?

2024-03-05 14:54 UTC, 1005hoon commented on login/index.js
> +  let passwordInput = document.querySelector('sign-input:nth-child(2)');
@hoonj170214 

```suggestion
  const emailInputEl = document.querySelector('input[type="email"]');
  const passwordInputEl = document.querySelector('input[type="password"]');
```


1. 변경되지 않을 요소의 경우, const로 변수 선언을 해주세요!
2. `input:nth-child`보다, 해당 Input이 지닌 type 프로퍼티 기준으로 선택자를 활용하는게 좋아보여요!

2024-03-05 14:54 UTC, 1005hoon commented on login/index.js
> +function showErrorMessage(emailErrorMessage, passwordErrorMessage) {
@hoonj170214 

한 함수가 두가지 작업을 처리하고 있네요! 
showErrormessage도 이메일 에러를 보여줄지, 비밀번호 에러를 보여줄지 구분해주고
각 에러를 보여주는 controller가 호출되는 타이밍에 맞춰 실행되도록 묶어보는건 어떨까요?

2024-03-05 14:54 UTC, 1005hoon commented on login/index.js
> +  }
@hoonj170214 

한 함수가 여러작업을 하는지 판단하기 좋은 방법은 이처럼 여러 요소에 대한 if else문의 활용입니다
한번 오늘 멘토링떄 이야기한 내용처럼 각 기능별로 분리해 리팩토링 해볼까요? 


또한 함수에서 실행할 요소와 DOM요소를 받아와 값을 처리하는 부분은 분리되는게 좋을것 같아요.
오늘 멘토링때 보여드린 예시처럼, DOM요소를 input으로 받고, ui controlling을 아웃풋으로 하는 함수와 
text value를 input으로 받고 그에 대한 로직 결과물을 아웃풋으로 하는 service로직이 분리되는 형태루요

2024-03-05 14:54 UTC, 1005hoon commented on login/index.js
> +});
@hoonj170214 

html Form 안에 button type="submit"이 존재한다면, 굳이 키다운 엔터 핸들링을 하지 않아도
엔터 입력 시 `submit` 액션이 발생하게 됩니다! 
이 경우, 자동으로 페이지가 새로고침되는데 이를 막는 형태로 한번 구현해보는건 어떨까요?

2024-03-05 23:07 UTC, hoonj170214 commented on index.html
> +    </nav>
감사합니다!

2024-03-05 23:22 UTC, hoonj170214 commented on index.html
> +      </div>
감사합니다! 수정했습니다. 한가지 궁금한 점이 있습니다.
cta 버튼 CSS는 랜딩페이지, 로그인, 회원가입에서 재사용됩니다.
classname을 hero-container__btn-cta 로 바꾸게 되면,
hero-container 에서만 쓸 수 있는 버튼으로 바뀌게 되는데, 
이때는 마크업 명확성과 재사용성 중에서 어떤 것을 우선해야할까요?

2024-03-05 23:32 UTC, hoonj170214 commented on index.html
> +    </header>
수정했습니다 감사합니다 👍

2024-03-05 23:34 UTC, hoonj170214 commented on index.html
> +    <article>
수정했습니다 감사합니다 👍

2024-03-06 03:53 UTC, hoonj170214 commented on login/index.js
> +}
에러 메세지를 위한 DOM을 만들기 보다는 textContent만 새로 할당해서 고쳐보겠습니다 감사합니다 👍

2024-03-06 03:57 UTC, hoonj170214 commented on login/index.js
> +  let passwordInput = document.querySelector('sign-input:nth-child(2)');
1. const 로 수정했습니다 
2. 이 부분에서 오류가 났었는데, `nth-child` 로 해서 그랬었네요. 감사합니다 👍

2024-03-06 03:58 UTC, hoonj170214 commented on login/index.js
> +function showErrorMessage(emailErrorMessage, passwordErrorMessage) {
이메일, 패스워드를 분리해라
라고 이해하면 될까요?

감사합니다 👍  수정하겠습니다

2024-03-06 04:05 UTC, hoonj170214 commented on login/index.js
> +});
`button type="submit"` 이면 엔트 입력시 `submit` 이 되는군요...
감사합니다 👍 
`event.preventDefault()`로 수정했습니다.

2024-03-06 05:03 UTC, hoonj170214 commented on login/index.js
> +  }
멘토님, 제가 이 부분에 대해서 이해가 부족한 것 같습니다. 
제가 이해한 내용을 적어보자면, 
- email , password 의 if-else 를 분리해라
- DOM 요소를 받는 부분 (`document.querySelector`) 와 함수 실행 부분(`if-else`) 를 분리해라

제가 잘 이해한게 맞나요?
일단 이해한대로 수정했습니다 감사합니다 👍

2024-03-06 05:03 UTC, hoonj170214 commented on index.html
> +      </section>
수정했습니다 감사합니다 👍

2024-03-06 05:03 UTC, hoonj170214 commented on signin.html
> +          </div>
수정했습니다 감사합니다 👍

2024-03-06 05:04 UTC, hoonj170214 commented on signin.html
> +          </div>
수정했습니다 감사합니다 👍

2024-03-06 23:26 UTC, hoonj170214 commented on login/index.js
> +  let passwordInput = document.querySelector('sign-input:nth-child(2)');
`const`가 아닌 `let` 으로 변수를 선언했던 이유는 
- const 는 변경(재할당)이 불가능한 상수
- `emailInput` , `passwordInput` 변수에 이벤트 핸들러를 등록하려면 변경(?)이 일어난다
- 따라서 `const`가 아닌 `let`으로 변경(재할당)할 수 있는 변수로 선언해야 한다
고 생각했었습니다. 일단 멘토님이 알려주신대로 수정 후에 다시 복습을 해보니 

그런데 제가 간과하고 있었던 부분이
- `const`로 선언된 변수는 재할당이 불가능하지만,  해당 변수가 참조하는 객체(DOM요소)의 내용은 변경될 수 있다.
- 변수가 참조하는 객체가 변하지 않는다는 `const`의 제약을 지키면서도 객체 내부의 속성 등은 변경될 수 있다.
였습니다. 

기본을 생각하지 못하고 있었네요ㅠ  알려주셔서 감사합니다 👍

2024-03-13 05:15 UTC, 1005hoon commented on index.html
> +      </div>
@hoonj170214 
좋은 질문이에요! 
이 경우 저번에 주현님이 멘토링에서 질문하셨던 내용과도 동일한데요
공통적으로 활용되는 디자인 시스템이 명확하게 나온 상황이라면 재사용성을 가져가야하겠지만 
기업 제품들의 보통의 경우 메인페이지의 CTA버튼과 로그인과 회원가입 폼 로그인 버튼 모양은 다릅니다. 

이를 위해 디자인 시스템에서 명확하게, primary button / secondary button 등과 같이 어디서 활용될지에 대한 약속이 명확하게 되어있다면 재사용성을 챙겨가는게 맞지만, 지금 디자인 시안에서는 동일한 스타일이여도 각각 다르게 마크업 목적으로 구현하는걸 개인적으로 선호하긴 합니다.

2024-03-13 05:15 UTC, 1005hoon commented on login/index.js
> +  let passwordInput = document.querySelector('sign-input:nth-child(2)');
@hoonj170214 

오 제대로 이해하셨습니다!
잘 하고 계시니 너무 걱정 마셔요 ㅋㅋ

2024-03-13 05:17 UTC, 1005hoon commented on login/index.js
> +  }
@hoonj170214 

아 조금 더 설명을 붙이자면, 특정한 경우 함수 내에서 다양한 요소들을 처리하고자 하여 if와 else if들이 들어가게 되는 경우가 많습니다.
이 경우를 조금 주의해야 하는데요. 

별 생각없이 코드를 작성하다보면 모든 케이스에 대해 다 대응할 수 있는 무적의 실버불릿 함수를 만드는 경우가 많이 발생하기 떄문이에요. 이처럼 비슷해보이는 모든 케이스에 대해 다 처리하는 함수의 경우 유지보수성이 확 나빠지게 됩니다.

따라서 한 함수에서 너무 많은 로직을 담당하고 있지는 않는가를 체크하는 가장 단순한 기준으로, `if / else - if`가 활용되는지를 개인적으로는 사용하고 있고. 이 경우 꼭 필요한 분기라면 유지하지만, 관심사에 따라 분리가 되어도 된다면 분리하는걸 개인적으로 선호합니다.

2024-03-13 05:20 UTC, 1005hoon approved these changes
@hoonj170214 


고생하셨습니다!
빠른 리뷰사이클로 하고자 하는 이야기는 얼추 끝난듯해요. 

이를 반영해서 week5 과제 진행하시면 될 것 같고, 
오늘 디코채널에 공유드린 영상 보면서 한번 관심사으 ㅣ분리 및 역할과 책임에 대해서 고민하며
리팩토링 해보면 더 좋은 코드가 될 것 같습니다.

고생 많으셨어요!

2024-03-15 01:44 UTC, merged